app = "ecfr-api"
primary_region = "iad"

[build]
  dockerfile = "./Dockerfile"

# ---- tell Fly exactly how to start the app -------------------------
[processes]
  app = ".venv/bin/uvicorn app:app --host 0.0.0.0 --port 8000"

[http_service]
  internal_port = 8000          # must match the port above
  processes     = ["app"]       # run that process
  force_https   = true
  auto_stop_machines  = "stop"
  auto_start_machines = true
  min_machines_running = 0
