app = "ecfr-api"

[build]
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 8000
  protocol      = "tcp"
  processes     = ["app"]

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
